name: Deploy (Dev) — Server Build Only
on:
  push:
    branches: [dev]
  workflow_dispatch:

# Keep newest run; auto-cancel older ones
concurrency:
  group: deploy-dev-build-only
  cancel-in-progress: true

jobs:
  build-and-server-compile:
    runs-on: ubuntu-latest
    # ensure environment-scoped secrets are available
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm (for web build on runner)
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ---------- WEB (build on runner, no deploy) ----------
      - name: Install & Build Web
        working-directory: apps/web
        run: |
          pnpm install
          pnpm build
          test -f dist/index.html

      - name: Package Web Dist (for visibility only)
        run: tar -C apps/web -czf web-dist.tar.gz dist

      # ---------- API (build on RUNNER; DO NOT rebuild on server) ----------
      - name: Install & Build API (runner precheck)
        working-directory: libs/api
        run: |
          pnpm install
          pnpm build
          ls -lah dist
          test -f dist/index.js

      - name: Package API Dist (no source, no node_modules)
        run: tar -C libs/api -czf api-dist.tar.gz dist

      # ---------- VERIFY ----------
      - name: Verify archives exist
        run: ls -lh web-dist.tar.gz api-dist.tar.gz

      # ---------- SECRETS PREFLIGHT ----------
      - name: Secrets preflight
        run: |
          [ -n "${{ secrets.LIGHTSAIL_HOST_DEV }}" ] || (echo "LIGHTSAIL_HOST_DEV missing" && exit 1)
          [ -n "${{ secrets.LIGHTSAIL_USER_DEV }}" ] || (echo "LIGHTSAIL_USER_DEV missing" && exit 1)
          [ -n "${{ secrets.LIGHTSAIL_SSH_KEY_DEV }}" ] || (echo "LIGHTSAIL_SSH_KEY_DEV missing" && exit 1)

      # ---------- UPLOAD ----------
      - name: Upload archives to server (/tmp)
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.LIGHTSAIL_HOST_DEV }}
          username: ${{ secrets.LIGHTSAIL_USER_DEV }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY_DEV }}
          source: "web-dist.tar.gz,api-dist.tar.gz"
          target: /tmp/
          debug: true

      # ---------- SERVER VERIFY (no rebuild, no pm2, no nginx) ----------
      - name: Verify builds on server in /tmp
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST_DEV }}
          username: ${{ secrets.LIGHTSAIL_USER_DEV }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY_DEV }}
          script_stop: true
          script: |
            set -euo pipefail
            SHA="${{ github.sha }}"
            WORK="/tmp/cp-build-${SHA:0:12}"

            echo "[server] preparing workdir: $WORK"
            rm -rf "$WORK"
            mkdir -p "$WORK/web-dist" "$WORK/api-dist"

            echo "[server] unpacking web dist"
            tar -xzf /tmp/web-dist.tar.gz -C "$WORK/web-dist"
            rm -f /tmp/web-dist.tar.gz || true
            test -f "$WORK/web-dist/index.html" || test -f "$WORK/web-dist/dist/index.html" || echo "[warn] web dist may be nested (ok)"

            echo "[server] unpacking api dist (prebuilt)"
            tar -xzf /tmp/api-dist.tar.gz -C "$WORK/api-dist"
            rm -f /tmp/api-dist.tar.gz

            echo "[server] verifying API build artifacts"
            test -f "$WORK/api-dist/dist/index.js"

            echo "[server] node version:"
            node -v || true

            echo "✅ Server received prebuilt artifacts at $WORK"
