name: Deploy (Dev) — Server-Side Build (Lightsail)

on:
  push:
    branches: [dev-deploy]
  workflow_dispatch:

concurrency:
  group: deploy-dev-lightsail
  cancel-in-progress: true

env:
  WEB_ROOT: /var/www/html/clintonprime
  CURRENT_API: /opt/clintonprime-site/current-api
  SITE_ROOT: /opt/clintonprime-site
  PM2_NAME: clintonprime-api-dev
  DOMAIN: dev.clintonprime.com
  EMAIL: clintonbess3@gmail.com
  REPO_DIR: /opt/clintonprime-site/repo
  REMOTE_USER: ${{ secrets.LIGHTSAIL_USER_DEV }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Secrets preflight
        run: |
          [ -n "${{ secrets.LIGHTSAIL_HOST_DEV }}" ] || (echo "LIGHTSAIL_HOST_DEV missing" && exit 1)
          [ -n "${{ secrets.LIGHTSAIL_USER_DEV }}" ] || (echo "LIGHTSAIL_USER_DEV missing" && exit 1)
          [ -n "${{ secrets.LIGHTSAIL_SSH_KEY_DEV }}" ] || (echo "LIGHTSAIL_SSH_KEY_DEV missing" && exit 1)

      - name: Bootstrap server (runs script from repo)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST_DEV }}
          username: ${{ secrets.LIGHTSAIL_USER_DEV }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY_DEV }}
          script_stop: true
          script: |
            set -euxo pipefail
            REPO_URL="https://github.com/${{ github.repository }}"
            REPO_DIR="${{ env.REPO_DIR }}"
            REMOTE_USER="${{ env.REMOTE_USER }}"

            # Ensure parent dir exists and is owned by the intended SSH user
            sudo mkdir -p "$(dirname "$REPO_DIR")"
            sudo chown -R "$REMOTE_USER:$REMOTE_USER" "$(dirname "$REPO_DIR")"
            [ -d "$REPO_DIR" ] || mkdir -p "$REPO_DIR"

            # Clone or fetch then checkout exact SHA
            if [ -d "$REPO_DIR/.git" ]; then
              git -C "$REPO_DIR" fetch --all --tags
            else
              git clone "$REPO_URL" "$REPO_DIR"
            fi
            cd "$REPO_DIR"
            git config core.fileMode false || true
            git reset --hard HEAD
            git clean -fd
            git checkout -q "${{ github.sha }}"
            chmod +x scripts/*.sh || true

            WEB_ROOT="${{ env.WEB_ROOT }}" \
            CURRENT_API="${{ env.CURRENT_API }}" \
            REPO_DIR="${{ env.REPO_DIR }}" \
            DOMAIN="${{ env.DOMAIN }}" \
            EMAIL="${{ env.EMAIL }}" \
            DEPLOY_USER="${{ env.REMOTE_USER }}" \
            bash scripts/bootstrap-dev.sh

      - name: Build & Deploy (runs script from repo)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST_DEV }}
          username: ${{ secrets.LIGHTSAIL_USER_DEV }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY_DEV }}
          script_stop: true
          script: |
            set -euxo pipefail
            REPO_DIR="${{ env.REPO_DIR }}"
            cd "$REPO_DIR"
            git fetch --all --tags
            git checkout -q "${{ github.sha }}"
            chmod +x scripts/*.sh || true

            # Render env.server with secrets and deployment settings
            cat > scripts/env.server <<'ENVV'
            export REMOTE_USER="${{ env.REMOTE_USER }}"
            export WEB_ROOT="${{ env.WEB_ROOT }}"
            export SITE_ROOT="${{ env.SITE_ROOT }}"
            export REPO_DIR="${{ env.REPO_DIR }}"
            export CURRENT_API="${{ env.CURRENT_API }}"
            export PM2_NAME="${{ env.PM2_NAME }}"
            export REPO_URL="https://github.com/${{ github.repository }}"
            export BRANCH=""            # using exact SHA for this workflow
            export SHA="${{ github.sha }}"

            # API runtime env
            export API_PORT="${{ secrets.API_PORT || '3000' }}"
            export SPOTIFY_CLIENT_ID="${{ secrets.SPOTIFY_CLIENT_ID }}"
            export SPOTIFY_CLIENT_SECRET="${{ secrets.SPOTIFY_CLIENT_SECRET }}"
            # leave empty to default to https://${{ env.DOMAIN }}/api/spotify/callback inside deploy.sh
            export SPOTIFY_REDIRECT_URI=""
            export SPOTIFY_REFRESH_TOKEN="${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
            export SPOTIFY_ACCESS_TOKEN="${{ secrets.SPOTIFY_ACCESS_TOKEN }}"
            ENNVV
            chmod 600 scripts/env.server || true

            # Run the unified deploy script
            bash scripts/deploy.sh
