name: Deploy (Dev) — Server-Side Build (Lightsail)

on:
  push:
    branches: [dev-deploy]
  workflow_dispatch:

concurrency:
  group: deploy-dev-lightsail
  cancel-in-progress: true

env:
  WEB_ROOT: /var/www/html/clintonprime
  CURRENT_API: /opt/clintonprime-site/current-api
  PM2_NAME: clintonprime-api-dev
  DOMAIN: dev.clintonprime.com
  EMAIL: clintonbess3@gmail.com
  DEPLOY_USER: ubuntu
  REPO_DIR: /opt/clintonprime-site/repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Secrets preflight
        run: |
          [ -n "${{ secrets.LIGHTSAIL_HOST_DEV }}" ] || (echo "LIGHTSAIL_HOST_DEV missing" && exit 1)
          [ -n "${{ secrets.LIGHTSAIL_USER_DEV }}" ] || (echo "LIGHTSAIL_USER_DEV missing" && exit 1)
          [ -n "${{ secrets.LIGHTSAIL_SSH_KEY_DEV }}" ] || (echo "LIGHTSAIL_SSH_KEY_DEV missing" && exit 1)

      - name: Bootstrap server (runs script from repo)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST_DEV }}
          username: ${{ secrets.LIGHTSAIL_USER_DEV }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY_DEV }}
          script_stop: true
          script: |
            set -euo pipefail
            REPO_URL="https://github.com/${{ github.repository }}"
            REPO_DIR="${{ env.REPO_DIR }}"
            [ -d "$REPO_DIR/.git" ] || { sudo mkdir -p "$(dirname "$REPO_DIR")"; git clone "$REPO_URL" "$REPO_DIR"; }
            cd "$REPO_DIR"
            git fetch --all --tags
            git checkout -q "${{ github.sha }}"
            chmod +x scripts/*.sh || true
            WEB_ROOT="${{ env.WEB_ROOT }}" \
            CURRENT_API="${{ env.CURRENT_API }}" \
            REPO_DIR="${{ env.REPO_DIR }}" \
            DOMAIN="${{ env.DOMAIN }}" \
            EMAIL="${{ env.EMAIL }}" \
            DEPLOY_USER="${{ env.DEPLOY_USER }}" \
            bash scripts/bootstrap-dev.sh

      - name: Build & Deploy (runs script from repo)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST_DEV }}
          username: ${{ secrets.LIGHTSAIL_USER_DEV }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY_DEV }}
          script_stop: true
          script: |
            set -euo pipefail
            REPO_URL="https://github.com/${{ github.repository }}"
            REPO_DIR="${{ env.REPO_DIR }}"
            cd "$REPO_DIR" || exit 1
            git fetch --all --tags
            git checkout -q "${{ github.sha }}"
            chmod +x scripts/*.sh || true
            REPO_URL="$REPO_URL" \
            REPO_DIR="$REPO_DIR" \
            WEB_ROOT="${{ env.WEB_ROOT }}" \
            CURRENT_API="${{ env.CURRENT_API }}" \
            PM2_NAME="${{ env.PM2_NAME }}" \
            SHA="${{ github.sha }}" \
            bash scripts/deploy-dev.sh
